name = "boxbi-chat"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "boxbi-db"
database_id = "821b47d1-16c3-4760-8590-d276d01ad085"

[[durable_objects.bindings]]
name = "CHAT_DO"
class_name = "ChatDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatDO"]

[vars]
JWT_SECRET = "super-secret-key"
